service: serverless-todo-app

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
    useChildProcesses: true

  dynamodb:
    start:
      port: 10000
      inMemory: true
      migrate: true
    stages:
      - ${self:provider.stage}

  s3:
    port: 12000
    directory: .s3
    cors: serverless-s3-local-cors.xml
    allowMismatchedSignatures: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    JWKS_ENDPOINT: ${env:JWKS_ENDPOINT}
    TODOS_TABLE_NAME: ${self:service}-${self:provider.stage}-todos-table
    ATTACHMENT_STORAGE: ${self:service}-${self:provider.stage}-attachment-v4

functions:
  Auth:
    handler: src/lambda/auth/auth0-authorizer.handler

  # DONE: Configure this function
  GetTodos:
    handler: src/lambda/http/get-todos.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE_NAME}"
    events:
      - http:
          method: get
          path: todos
          cors: true
          authorizer:
            name: Auth

  # DONE: Configure this function
  CreateTodo:
    handler: src/lambda/http/create-todo.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE_NAME}"
    events:
      - http:
          method: post
          path: todos
          cors: true
          authorizer:
            name: Auth

  # DONE: Configure this function
  UpdateTodo:
    handler: src/lambda/http/update-todo.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE_NAME}"
    events:
      - http:
          method: patch
          path: todos/{todoId}
          cors: true
          authorizer:
            name: Auth

  # DONE: Configure this function
  DeleteTodo:
    handler: src/lambda/http/delete-todo.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE_NAME}"
    events:
      - http:
          method: delete
          path: todos/{todoId}
          cors: true
          authorizer:
            name: Auth

  # DONE: Configure this function
  GenerateUploadUrl:
    handler: src/lambda/http/generate-upload-url.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: "arn:aws:s3:::${self:provider.environment.ATTACHMENT_STORAGE}/*"
    events:
      - http:
          method: post
          path: todos/{todoId}/attachment
          cors: true
          authorizer:
            name: Auth

resources:
  Resources:
    # DONE: Add any necessary AWS resources
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TODOS_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: todoId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: todoId
            KeyType: RANGE

    AttachmentStorage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.ATTACHMENT_STORAGE}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders: ["*"]
              AllowedMethods: [GET, PUT]
              MaxAge: 3600
